projects:
  - Gate Service:
      alias: "gate"
      path: "d:\\projects\\go\\projectmaker"
  - Tracker Service:
      alias: "tracker"
      path: "d:\\projects\\go\\tracker\\"

# Git configuration is used to create new pull requests
git:
  remote_name: "origin"
  source_branch: "master"
  server: "http://gitlab.com"
  token: ""

pull_request_reviewers:
  - "u1"
  - "u2"