projects:
  - Orders Service:
      project_id: "orders"
      path: "/path_to_project/orders"

# Git configuration is used to create new pull requests
# Pull request will be created to http://gitlab.com/[repository_id]/[project_id]
git:
  enable: true
  repository_id: "microservices"
  remote_name: "origin"
  main_branch: "master"
  server: "http://gitlab.com"
  token: ""

pull_request:
  authors:
    - "a1"
  reviewers:
    - "r1"
    - "r2"